CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Official Keyball sensor is PMW3360 (not PMW3610).
CONFIG_PMW3360=y
CONFIG_PMW3360_CPI=1200
CONFIG_PMW3360_CPI_DIVIDOR=4
CONFIG_PMW3360_ORIENTATION_180=y
CONFIG_PMW3360_SNIPE_CPI=400
CONFIG_PMW3360_SNIPE_CPI_DIVIDOR=4

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
